# -*- mode: ruby -*-
# vi: set ft=ruby :


MACHINES = {
  :zfs => {
        # :box_name => "constantlux/ubuntu-22.04_kernel-6.6.1",
        :box_name => "constantlux/ubuntu-22.04",
        # :box_ver => "0.1.1",
        :ip_addr => '192.168.57.150',
        :disks => {
          :sata1 => {
            :dfile => './sata1.vdi',
            :size => 512,
            :port => 1
          },
          :sata2 => {
            :dfile => './sata2.vdi',
            :size => 512,
            :port => 2
          },
          :sata3 => {
            :dfile => './sata3.vdi',
            :size => 512,
            :port => 3
          },
          :sata4 => {
            :dfile => './sata4.vdi',
            :size => 512,
            :port => 4
          },
          :sata5 => {
            :dfile => './sata5.vdi',
            :size => 512,
            :port => 5
          },
         :sata6 => {
            :dfile => './sata6.vdi',
            :size => 512,
            :port => 6
          },
         :sata7 => {
            :dfile => './sata7.vdi',
            :size => 512,
            :port => 7
          },
          :sata8 => {
            :dfile => './sata8.vdi',
            :size => 512,
            :port => 8
          }
        }
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.box_version = boxconfig[:box_ver]
          box.vm.host_name = boxname.to_s
          
          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
            # Begine for Task5
            needsController = false
            boxconfig[:disks].each do |dname, dconf|
              unless File.exist?(dconf[:dfile])
                vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                needsController =  true
              end
            end
            if needsController == true
              vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
              boxconfig[:disks].each do |dname, dconf|
                vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
              end
            end
            config.vm.provision "shell", inline: <<-SHELL
              # 0.Install
              sudo su
              apt update
              apt install zfsutils-linux -y
              modprobe zfs
            SHELL
          end
       end
  end
end
 

