# -*- mode: ruby -*-
# vi: set ft=ruby :
MACHINES = {
    :PAM => {
        :box_name => "constantlux/ubuntu-22.04",
        :ip_addr => '192.168.57.150',
        :script => 'scripts/build.sh',
        :addusr => 'scripts/addusr.sh'
  }

}
Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "1024"]
            end
            box.vm.provision "shell",path: boxconfig[:script]
            box.vm.provision "file", source: "scripts/login.sh", destination: "/home/vagrant/login.sh"
            box.vm.provision "shell",path: boxconfig[:addusr]
            
        end
    end
end
