# -*- mode: ruby -*-
# vi: set ft=ruby :
MACHINES = {
    :nginx => {
        :box_name => "constantlux/ubuntu-22.04",
        :ip_addr => '192.168.57.150',
        :script => 'scripts/build.sh'
  }

}
Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "2048"]
            end
            box.vm.provision "file", source: "files/apache_logs", destination: "/home/vagrant/apache_logs"
            box.vm.provision "file", source: "files/script.sh", destination: "/home/vagrant/script.sh"
            box.vm.provision "shell",path: boxconfig[:script]
        end
    end
end
