# -*- mode: ruby -*-
# vi: set ft=ruby :


MACHINES = {
  :nginx => {
        :box_name => "constantlux/ubuntu-20.04_kernel-6.6.1",
        :ip_addr => '192.168.57.150'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
          end
        

      end
  end
end
 

